### ISSUE TITLE
installation problems "rake install" - ione

### ISSUE THREAD

**Issue by chicco64** [ione-cloud/ione#82]
Hi !
I have attempted to install ion following your recommendations:
- Centos 8 
- Opennebula 5.12.3
- node --version v14.16.0
- mysqladmin  Ver 8.0.21
- ruby 2.5.5p157
but the installation ends with the following error messages:
<img width="703" alt="errore_ione_opennebula" src="https://user-images.githubusercontent.com/59960414/111076495-62354400-84e4-11eb-856a-13ef7ae8d593.PNG">
<img width="1098" alt="errore_ione_opennebula2" src="https://user-images.githubusercontent.com/59960414/111076497-66616180-84e4-11eb-858b-20b7b5effb63.PNG">
Maybe I'm doing something wrong, can you help me? thank you

**Comment by slntopp** [comment]
Hi @chicco64 
You could checkout code from v1.0.2 branch, this problem should have been fixed there.

Let us know if it worked out, thanks

**Comment by chicco64** [comment]
Hi !
Sorry, but I do not understand....
after running "rake install" do I have to run some other command? I have repeated the installation several times but the error persists. thanks

**Comment by slntopp** [comment]
1. `cd` to the directory you cloned repo to
2. `git checkout v1.0.2`
3. `git pull`
4. `rake install`

I would also recommend to revert installation before running this again, or at least 
`rm -rf /usr/lib/one/ione /usr/lib/systemd/system/ione.service /etc/one/ione.conf`

**Comment by chicco64** [comment]
Hi !
I did the installation again with the changes indicated, with a better result;

- nginx is active and opennebula is visible in https://
- IONe does not activate through "systemctl start ione"
- IONe UI is visible through https: //ione-admin (what are the login credentials?)

<img width="594" alt="test_ione2" src="https://user-images.githubusercontent.com/59960414/111197766-c3c5e300-85b6-11eb-8f5c-37a22e2a87f7.PNG">

- Now report the new error messages:
- 
<img width="759" alt="test_ione1" src="https://user-images.githubusercontent.com/59960414/111197798-ccb6b480-85b6-11eb-88fa-d566863076bf.PNG">

Thank you again for the final help !

**Comment by slntopp** [comment]
> IONe UI is visible through https: //ione-admin (what are the login credentials?)
These are ONe user credentials. IONe Admin UI let's any admin user in(admin means one admin group member)

**Comment by slntopp** [comment]
> IONe does not activate through "systemctl start ione"

Could you please share some more logs either from `journalctl` or by running `ruby /usr/lib/one/ione/ione_server.rb` as oneadmin?

**Comment by chicco64** [comment]
Hi !
this is the result 

[oneadmin@opennebula-frontend ~]$ ruby /usr/lib/one/ione/ione_server.rb

Getting path to the server
Including log-library
Checking service version
Setting up Environment(OpenNebula API)
Traceback (most recent call last):
        2: from /usr/lib/one/ione/ione_server.rb:90:in `<main>'
        1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- core/* (LoadError)

**Comment by slntopp** [comment]
Hi, Make sure your `/usr/lib/one/ione/core/` directory looks like this:

<img width="406" alt="Screenshot 2021-03-16 at 17 36 35" src="https://user-images.githubusercontent.com/32666515/111346074-28984080-867e-11eb-83b5-89eb2af08bdc.png">

**Comment by chicco64** [comment]
ok 
cp -r ione/core  /usr/lib/one/ione
this is the result !

<img width="829" alt="mod1" src="https://user-images.githubusercontent.com/59960414/111350506-19af8f00-867a-11eb-950b-b0a6801612dc.PNG">
<img width="1010" alt="mod2" src="https://user-images.githubusercontent.com/59960414/111350526-1d431600-867a-11eb-8a5b-d0626c4c2176.PNG">
Is it possible to enter the ui interface? what are the credentials?
<img width="592" alt="mod3" src="https://user-images.githubusercontent.com/59960414/111350535-1f0cd980-867a-11eb-97ce-7aa652dfeb3c.PNG">

I await new instructions. thank you

**Comment by slntopp** [comment]
By your screenshot IONe is running now
Just use your oneadmin credentials at ione-admin
Classic opennebula UI(Sunstone) would be available at cloud.yourdomain by default

Closing this Issue
